/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtistProfileAddRecord
 */
export interface ArtistProfileAddRecord {
    /**
     * 
     * @type {string}
     * @memberof ArtistProfileAddRecord
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArtistProfileAddRecord
     */
    userId: string;
}

/**
 * Check if a given object implements the ArtistProfileAddRecord interface.
 */
export function instanceOfArtistProfileAddRecord(value: object): value is ArtistProfileAddRecord {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ArtistProfileAddRecordFromJSON(json: any): ArtistProfileAddRecord {
    return ArtistProfileAddRecordFromJSONTyped(json, false);
}

export function ArtistProfileAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistProfileAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'] == null ? undefined : json['bio'],
        'userId': json['userId'],
    };
}

export function ArtistProfileAddRecordToJSON(json: any): ArtistProfileAddRecord {
    return ArtistProfileAddRecordToJSONTyped(json, false);
}

export function ArtistProfileAddRecordToJSONTyped(value?: ArtistProfileAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'userId': value['userId'],
    };
}

