/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtistProfileRecord
 */
export interface ArtistProfileRecord {
    /**
     * 
     * @type {string}
     * @memberof ArtistProfileRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ArtistProfileRecord
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArtistProfileRecord
     */
    userId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArtistProfileRecord
     */
    artworkIds?: Array<string> | null;
}

/**
 * Check if a given object implements the ArtistProfileRecord interface.
 */
export function instanceOfArtistProfileRecord(value: object): value is ArtistProfileRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ArtistProfileRecordFromJSON(json: any): ArtistProfileRecord {
    return ArtistProfileRecordFromJSONTyped(json, false);
}

export function ArtistProfileRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistProfileRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'userId': json['userId'],
        'artworkIds': json['artworkIds'] == null ? undefined : json['artworkIds'],
    };
}

export function ArtistProfileRecordToJSON(json: any): ArtistProfileRecord {
    return ArtistProfileRecordToJSONTyped(json, false);
}

export function ArtistProfileRecordToJSONTyped(value?: ArtistProfileRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bio': value['bio'],
        'userId': value['userId'],
        'artworkIds': value['artworkIds'],
    };
}

