/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtistProfileUpdateRecord
 */
export interface ArtistProfileUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof ArtistProfileUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ArtistProfileUpdateRecord
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArtistProfileUpdateRecord
     */
    userId: string;
}

/**
 * Check if a given object implements the ArtistProfileUpdateRecord interface.
 */
export function instanceOfArtistProfileUpdateRecord(value: object): value is ArtistProfileUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ArtistProfileUpdateRecordFromJSON(json: any): ArtistProfileUpdateRecord {
    return ArtistProfileUpdateRecordFromJSONTyped(json, false);
}

export function ArtistProfileUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistProfileUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'userId': json['userId'],
    };
}

export function ArtistProfileUpdateRecordToJSON(json: any): ArtistProfileUpdateRecord {
    return ArtistProfileUpdateRecordToJSONTyped(json, false);
}

export function ArtistProfileUpdateRecordToJSONTyped(value?: ArtistProfileUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bio': value['bio'],
        'userId': value['userId'],
    };
}

