/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtworkRecord
 */
export interface ArtworkRecord {
    /**
     * 
     * @type {string}
     * @memberof ArtworkRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ArtworkRecord
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ArtworkRecord
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ArtworkRecord
     */
    imageUrl: string;
    /**
     * 
     * @type {number}
     * @memberof ArtworkRecord
     */
    views: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkRecord
     */
    shares: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkRecord
     */
    likes: number;
    /**
     * 
     * @type {string}
     * @memberof ArtworkRecord
     */
    artistProfileId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArtworkRecord
     */
    tagIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArtworkRecord
     */
    collectionIds?: Array<string> | null;
}

/**
 * Check if a given object implements the ArtworkRecord interface.
 */
export function instanceOfArtworkRecord(value: object): value is ArtworkRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('views' in value) || value['views'] === undefined) return false;
    if (!('shares' in value) || value['shares'] === undefined) return false;
    if (!('likes' in value) || value['likes'] === undefined) return false;
    if (!('artistProfileId' in value) || value['artistProfileId'] === undefined) return false;
    return true;
}

export function ArtworkRecordFromJSON(json: any): ArtworkRecord {
    return ArtworkRecordFromJSONTyped(json, false);
}

export function ArtworkRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtworkRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'imageUrl': json['imageUrl'],
        'views': json['views'],
        'shares': json['shares'],
        'likes': json['likes'],
        'artistProfileId': json['artistProfileId'],
        'tagIds': json['tagIds'] == null ? undefined : json['tagIds'],
        'collectionIds': json['collectionIds'] == null ? undefined : json['collectionIds'],
    };
}

export function ArtworkRecordToJSON(json: any): ArtworkRecord {
    return ArtworkRecordToJSONTyped(json, false);
}

export function ArtworkRecordToJSONTyped(value?: ArtworkRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'imageUrl': value['imageUrl'],
        'views': value['views'],
        'shares': value['shares'],
        'likes': value['likes'],
        'artistProfileId': value['artistProfileId'],
        'tagIds': value['tagIds'],
        'collectionIds': value['collectionIds'],
    };
}

