/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ArtworkOrderEnum = {
    Random: 'Random',
    Newest: 'Newest',
    Oldest: 'Oldest',
    MostLiked: 'MostLiked',
    MostViewed: 'MostViewed'
} as const;
export type ArtworkOrderEnum = typeof ArtworkOrderEnum[keyof typeof ArtworkOrderEnum];


export function instanceOfArtworkOrderEnum(value: any): boolean {
    for (const key in ArtworkOrderEnum) {
        if (Object.prototype.hasOwnProperty.call(ArtworkOrderEnum, key)) {
            if (ArtworkOrderEnum[key as keyof typeof ArtworkOrderEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ArtworkOrderEnumFromJSON(json: any): ArtworkOrderEnum {
    return ArtworkOrderEnumFromJSONTyped(json, false);
}

export function ArtworkOrderEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtworkOrderEnum {
    return json as ArtworkOrderEnum;
}

export function ArtworkOrderEnumToJSON(value?: ArtworkOrderEnum | null): any {
    return value as any;
}

export function ArtworkOrderEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ArtworkOrderEnum {
    return value as ArtworkOrderEnum;
}

