/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionArtworkRecord
 */
export interface CollectionArtworkRecord {
    /**
     * 
     * @type {string}
     * @memberof CollectionArtworkRecord
     */
    collectionId: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionArtworkRecord
     */
    artworkId: string;
}

/**
 * Check if a given object implements the CollectionArtworkRecord interface.
 */
export function instanceOfCollectionArtworkRecord(value: object): value is CollectionArtworkRecord {
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('artworkId' in value) || value['artworkId'] === undefined) return false;
    return true;
}

export function CollectionArtworkRecordFromJSON(json: any): CollectionArtworkRecord {
    return CollectionArtworkRecordFromJSONTyped(json, false);
}

export function CollectionArtworkRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionArtworkRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionId': json['collectionId'],
        'artworkId': json['artworkId'],
    };
}

export function CollectionArtworkRecordToJSON(json: any): CollectionArtworkRecord {
    return CollectionArtworkRecordToJSONTyped(json, false);
}

export function CollectionArtworkRecordToJSONTyped(value?: CollectionArtworkRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collectionId': value['collectionId'],
        'artworkId': value['artworkId'],
    };
}

