/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionRecord
 */
export interface CollectionRecord {
    /**
     * 
     * @type {string}
     * @memberof CollectionRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionRecord
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionRecord
     */
    isPrivate: boolean;
    /**
     * 
     * @type {string}
     * @memberof CollectionRecord
     */
    userId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CollectionRecord
     */
    artworkIds?: Array<string> | null;
}

/**
 * Check if a given object implements the CollectionRecord interface.
 */
export function instanceOfCollectionRecord(value: object): value is CollectionRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isPrivate' in value) || value['isPrivate'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CollectionRecordFromJSON(json: any): CollectionRecord {
    return CollectionRecordFromJSONTyped(json, false);
}

export function CollectionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isPrivate': json['isPrivate'],
        'userId': json['userId'],
        'artworkIds': json['artworkIds'] == null ? undefined : json['artworkIds'],
    };
}

export function CollectionRecordToJSON(json: any): CollectionRecord {
    return CollectionRecordToJSONTyped(json, false);
}

export function CollectionRecordToJSONTyped(value?: CollectionRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'isPrivate': value['isPrivate'],
        'userId': value['userId'],
        'artworkIds': value['artworkIds'],
    };
}

