/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionUpdateRecord
 */
export interface CollectionUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof CollectionUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionUpdateRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionUpdateRecord
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionUpdateRecord
     */
    isPrivate: boolean;
    /**
     * 
     * @type {string}
     * @memberof CollectionUpdateRecord
     */
    userId: string;
}

/**
 * Check if a given object implements the CollectionUpdateRecord interface.
 */
export function instanceOfCollectionUpdateRecord(value: object): value is CollectionUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isPrivate' in value) || value['isPrivate'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CollectionUpdateRecordFromJSON(json: any): CollectionUpdateRecord {
    return CollectionUpdateRecordFromJSONTyped(json, false);
}

export function CollectionUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isPrivate': json['isPrivate'],
        'userId': json['userId'],
    };
}

export function CollectionUpdateRecordToJSON(json: any): CollectionUpdateRecord {
    return CollectionUpdateRecordToJSONTyped(json, false);
}

export function CollectionUpdateRecordToJSONTyped(value?: CollectionUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'isPrivate': value['isPrivate'],
        'userId': value['userId'],
    };
}

