/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionAddRecord
 */
export interface CollectionAddRecord {
    /**
     * 
     * @type {string}
     * @memberof CollectionAddRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionAddRecord
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionAddRecord
     */
    isPrivate: boolean;
    /**
     * 
     * @type {string}
     * @memberof CollectionAddRecord
     */
    userId: string;
}

/**
 * Check if a given object implements the CollectionAddRecord interface.
 */
export function instanceOfCollectionAddRecord(value: object): value is CollectionAddRecord {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isPrivate' in value) || value['isPrivate'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CollectionAddRecordFromJSON(json: any): CollectionAddRecord {
    return CollectionAddRecordFromJSONTyped(json, false);
}

export function CollectionAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isPrivate': json['isPrivate'],
        'userId': json['userId'],
    };
}

export function CollectionAddRecordToJSON(json: any): CollectionAddRecord {
    return CollectionAddRecordToJSONTyped(json, false);
}

export function CollectionAddRecordToJSONTyped(value?: CollectionAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'isPrivate': value['isPrivate'],
        'userId': value['userId'],
    };
}

