/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ErrorCodes = {
    Unknown: 'Unknown',
    TechnicalError: 'TechnicalError',
    EntityNotFound: 'EntityNotFound',
    EntityAlreadyExists: 'EntityAlreadyExists',
    AccessDenied: 'AccessDenied',
    PhysicalFileNotFound: 'PhysicalFileNotFound',
    UserAlreadyExists: 'UserAlreadyExists',
    WrongPassword: 'WrongPassword',
    CannotAdd: 'CannotAdd',
    CannotUpdate: 'CannotUpdate',
    CannotDelete: 'CannotDelete',
    MailSendFailed: 'MailSendFailed'
} as const;
export type ErrorCodes = typeof ErrorCodes[keyof typeof ErrorCodes];


export function instanceOfErrorCodes(value: any): boolean {
    for (const key in ErrorCodes) {
        if (Object.prototype.hasOwnProperty.call(ErrorCodes, key)) {
            if (ErrorCodes[key as keyof typeof ErrorCodes] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ErrorCodesFromJSON(json: any): ErrorCodes {
    return ErrorCodesFromJSONTyped(json, false);
}

export function ErrorCodesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorCodes {
    return json as ErrorCodes;
}

export function ErrorCodesToJSON(value?: ErrorCodes | null): any {
    return value as any;
}

export function ErrorCodesToJSONTyped(value: any, ignoreDiscriminator: boolean): ErrorCodes {
    return value as ErrorCodes;
}

