/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackOptionRecord
 */
export interface FeedbackOptionRecord {
    /**
     * 
     * @type {string}
     * @memberof FeedbackOptionRecord
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackOptionRecord
     */
    satisfactionLevel: string;
}

/**
 * Check if a given object implements the FeedbackOptionRecord interface.
 */
export function instanceOfFeedbackOptionRecord(value: object): value is FeedbackOptionRecord {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('satisfactionLevel' in value) || value['satisfactionLevel'] === undefined) return false;
    return true;
}

export function FeedbackOptionRecordFromJSON(json: any): FeedbackOptionRecord {
    return FeedbackOptionRecordFromJSONTyped(json, false);
}

export function FeedbackOptionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackOptionRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'satisfactionLevel': json['satisfactionLevel'],
    };
}

export function FeedbackOptionRecordToJSON(json: any): FeedbackOptionRecord {
    return FeedbackOptionRecordToJSONTyped(json, false);
}

export function FeedbackOptionRecordToJSONTyped(value?: FeedbackOptionRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'satisfactionLevel': value['satisfactionLevel'],
    };
}

