/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedbackOptionRecord } from './FeedbackOptionRecord';
import {
    FeedbackOptionRecordFromJSON,
    FeedbackOptionRecordFromJSONTyped,
    FeedbackOptionRecordToJSON,
    FeedbackOptionRecordToJSONTyped,
} from './FeedbackOptionRecord';

/**
 * 
 * @export
 * @interface FeedbackSubmitRecord
 */
export interface FeedbackSubmitRecord {
    /**
     * 
     * @type {Array<FeedbackOptionRecord>}
     * @memberof FeedbackSubmitRecord
     */
    options: Array<FeedbackOptionRecord>;
    /**
     * 
     * @type {string}
     * @memberof FeedbackSubmitRecord
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackSubmitRecord
     */
    contactReason: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackSubmitRecord
     */
    contactEmail: string | null;
}

/**
 * Check if a given object implements the FeedbackSubmitRecord interface.
 */
export function instanceOfFeedbackSubmitRecord(value: object): value is FeedbackSubmitRecord {
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('contactReason' in value) || value['contactReason'] === undefined) return false;
    if (!('contactEmail' in value) || value['contactEmail'] === undefined) return false;
    return true;
}

export function FeedbackSubmitRecordFromJSON(json: any): FeedbackSubmitRecord {
    return FeedbackSubmitRecordFromJSONTyped(json, false);
}

export function FeedbackSubmitRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackSubmitRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'options': ((json['options'] as Array<any>).map(FeedbackOptionRecordFromJSON)),
        'message': json['message'],
        'contactReason': json['contactReason'],
        'contactEmail': json['contactEmail'],
    };
}

export function FeedbackSubmitRecordToJSON(json: any): FeedbackSubmitRecord {
    return FeedbackSubmitRecordToJSONTyped(json, false);
}

export function FeedbackSubmitRecordToJSONTyped(value?: FeedbackSubmitRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'options': ((value['options'] as Array<any>).map(FeedbackOptionRecordToJSON)),
        'message': value['message'],
        'contactReason': value['contactReason'],
        'contactEmail': value['contactEmail'],
    };
}

