/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserFileRecord } from './UserFileRecord';
import {
    UserFileRecordFromJSON,
    UserFileRecordFromJSONTyped,
    UserFileRecordToJSON,
    UserFileRecordToJSONTyped,
} from './UserFileRecord';

/**
 * 
 * @export
 * @interface PagedResponseOfUserFileRecord
 */
export interface PagedResponseOfUserFileRecord {
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfUserFileRecord
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfUserFileRecord
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfUserFileRecord
     */
    totalCount: number;
    /**
     * 
     * @type {Array<UserFileRecord>}
     * @memberof PagedResponseOfUserFileRecord
     */
    data: Array<UserFileRecord>;
}

/**
 * Check if a given object implements the PagedResponseOfUserFileRecord interface.
 */
export function instanceOfPagedResponseOfUserFileRecord(value: object): value is PagedResponseOfUserFileRecord {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PagedResponseOfUserFileRecordFromJSON(json: any): PagedResponseOfUserFileRecord {
    return PagedResponseOfUserFileRecordFromJSONTyped(json, false);
}

export function PagedResponseOfUserFileRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseOfUserFileRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(UserFileRecordFromJSON)),
    };
}

export function PagedResponseOfUserFileRecordToJSON(json: any): PagedResponseOfUserFileRecord {
    return PagedResponseOfUserFileRecordToJSONTyped(json, false);
}

export function PagedResponseOfUserFileRecordToJSONTyped(value?: PagedResponseOfUserFileRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(UserFileRecordToJSON)),
    };
}

