/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRecord } from './UserRecord';
import {
    UserRecordFromJSON,
    UserRecordFromJSONTyped,
    UserRecordToJSON,
    UserRecordToJSONTyped,
} from './UserRecord';

/**
 * 
 * @export
 * @interface PagedResponseOfUserRecord
 */
export interface PagedResponseOfUserRecord {
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfUserRecord
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfUserRecord
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfUserRecord
     */
    totalCount: number;
    /**
     * 
     * @type {Array<UserRecord>}
     * @memberof PagedResponseOfUserRecord
     */
    data: Array<UserRecord>;
}

/**
 * Check if a given object implements the PagedResponseOfUserRecord interface.
 */
export function instanceOfPagedResponseOfUserRecord(value: object): value is PagedResponseOfUserRecord {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PagedResponseOfUserRecordFromJSON(json: any): PagedResponseOfUserRecord {
    return PagedResponseOfUserRecordFromJSONTyped(json, false);
}

export function PagedResponseOfUserRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseOfUserRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(UserRecordFromJSON)),
    };
}

export function PagedResponseOfUserRecordToJSON(json: any): PagedResponseOfUserRecord {
    return PagedResponseOfUserRecordToJSONTyped(json, false);
}

export function PagedResponseOfUserRecordToJSONTyped(value?: PagedResponseOfUserRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(UserRecordToJSON)),
    };
}

