/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArtworkRecord } from './ArtworkRecord';
import {
    ArtworkRecordFromJSON,
    ArtworkRecordFromJSONTyped,
    ArtworkRecordToJSON,
    ArtworkRecordToJSONTyped,
} from './ArtworkRecord';

/**
 * 
 * @export
 * @interface PagedResponseOfArtworkRecord
 */
export interface PagedResponseOfArtworkRecord {
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfArtworkRecord
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfArtworkRecord
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfArtworkRecord
     */
    totalCount: number;
    /**
     * 
     * @type {Array<ArtworkRecord>}
     * @memberof PagedResponseOfArtworkRecord
     */
    data: Array<ArtworkRecord>;
}

/**
 * Check if a given object implements the PagedResponseOfArtworkRecord interface.
 */
export function instanceOfPagedResponseOfArtworkRecord(value: object): value is PagedResponseOfArtworkRecord {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PagedResponseOfArtworkRecordFromJSON(json: any): PagedResponseOfArtworkRecord {
    return PagedResponseOfArtworkRecordFromJSONTyped(json, false);
}

export function PagedResponseOfArtworkRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseOfArtworkRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(ArtworkRecordFromJSON)),
    };
}

export function PagedResponseOfArtworkRecordToJSON(json: any): PagedResponseOfArtworkRecord {
    return PagedResponseOfArtworkRecordToJSONTyped(json, false);
}

export function PagedResponseOfArtworkRecordToJSONTyped(value?: PagedResponseOfArtworkRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(ArtworkRecordToJSON)),
    };
}

