/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArtistProfileRecord } from './ArtistProfileRecord';
import {
    ArtistProfileRecordFromJSON,
    ArtistProfileRecordFromJSONTyped,
    ArtistProfileRecordToJSON,
    ArtistProfileRecordToJSONTyped,
} from './ArtistProfileRecord';

/**
 * 
 * @export
 * @interface PagedResponseOfArtistProfileRecord
 */
export interface PagedResponseOfArtistProfileRecord {
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfArtistProfileRecord
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfArtistProfileRecord
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfArtistProfileRecord
     */
    totalCount: number;
    /**
     * 
     * @type {Array<ArtistProfileRecord>}
     * @memberof PagedResponseOfArtistProfileRecord
     */
    data: Array<ArtistProfileRecord>;
}

/**
 * Check if a given object implements the PagedResponseOfArtistProfileRecord interface.
 */
export function instanceOfPagedResponseOfArtistProfileRecord(value: object): value is PagedResponseOfArtistProfileRecord {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PagedResponseOfArtistProfileRecordFromJSON(json: any): PagedResponseOfArtistProfileRecord {
    return PagedResponseOfArtistProfileRecordFromJSONTyped(json, false);
}

export function PagedResponseOfArtistProfileRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseOfArtistProfileRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(ArtistProfileRecordFromJSON)),
    };
}

export function PagedResponseOfArtistProfileRecordToJSON(json: any): PagedResponseOfArtistProfileRecord {
    return PagedResponseOfArtistProfileRecordToJSONTyped(json, false);
}

export function PagedResponseOfArtistProfileRecordToJSONTyped(value?: PagedResponseOfArtistProfileRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(ArtistProfileRecordToJSON)),
    };
}

