/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagRecord } from './TagRecord';
import {
    TagRecordFromJSON,
    TagRecordFromJSONTyped,
    TagRecordToJSON,
    TagRecordToJSONTyped,
} from './TagRecord';

/**
 * 
 * @export
 * @interface PagedResponseOfTagRecord
 */
export interface PagedResponseOfTagRecord {
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfTagRecord
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfTagRecord
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfTagRecord
     */
    totalCount: number;
    /**
     * 
     * @type {Array<TagRecord>}
     * @memberof PagedResponseOfTagRecord
     */
    data: Array<TagRecord>;
}

/**
 * Check if a given object implements the PagedResponseOfTagRecord interface.
 */
export function instanceOfPagedResponseOfTagRecord(value: object): value is PagedResponseOfTagRecord {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PagedResponseOfTagRecordFromJSON(json: any): PagedResponseOfTagRecord {
    return PagedResponseOfTagRecordFromJSONTyped(json, false);
}

export function PagedResponseOfTagRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseOfTagRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(TagRecordFromJSON)),
    };
}

export function PagedResponseOfTagRecordToJSON(json: any): PagedResponseOfTagRecord {
    return PagedResponseOfTagRecordToJSONTyped(json, false);
}

export function PagedResponseOfTagRecordToJSONTyped(value?: PagedResponseOfTagRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(TagRecordToJSON)),
    };
}

