/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionRecord } from './CollectionRecord';
import {
    CollectionRecordFromJSON,
    CollectionRecordFromJSONTyped,
    CollectionRecordToJSON,
    CollectionRecordToJSONTyped,
} from './CollectionRecord';

/**
 * 
 * @export
 * @interface PagedResponseOfCollectionRecord
 */
export interface PagedResponseOfCollectionRecord {
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfCollectionRecord
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfCollectionRecord
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseOfCollectionRecord
     */
    totalCount: number;
    /**
     * 
     * @type {Array<CollectionRecord>}
     * @memberof PagedResponseOfCollectionRecord
     */
    data: Array<CollectionRecord>;
}

/**
 * Check if a given object implements the PagedResponseOfCollectionRecord interface.
 */
export function instanceOfPagedResponseOfCollectionRecord(value: object): value is PagedResponseOfCollectionRecord {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PagedResponseOfCollectionRecordFromJSON(json: any): PagedResponseOfCollectionRecord {
    return PagedResponseOfCollectionRecordFromJSONTyped(json, false);
}

export function PagedResponseOfCollectionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseOfCollectionRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(CollectionRecordFromJSON)),
    };
}

export function PagedResponseOfCollectionRecordToJSON(json: any): PagedResponseOfCollectionRecord {
    return PagedResponseOfCollectionRecordToJSONTyped(json, false);
}

export function PagedResponseOfCollectionRecordToJSONTyped(value?: PagedResponseOfCollectionRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(CollectionRecordToJSON)),
    };
}

