/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterRecord
 */
export interface RegisterRecord {
    /**
     * 
     * @type {string}
     * @memberof RegisterRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRecord
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRecord
     */
    password: string;
}

/**
 * Check if a given object implements the RegisterRecord interface.
 */
export function instanceOfRegisterRecord(value: object): value is RegisterRecord {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegisterRecordFromJSON(json: any): RegisterRecord {
    return RegisterRecordFromJSONTyped(json, false);
}

export function RegisterRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function RegisterRecordToJSON(json: any): RegisterRecord {
    return RegisterRecordToJSONTyped(json, false);
}

export function RegisterRecordToJSONTyped(value?: RegisterRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
    };
}

