/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArtistProfileRecord } from './ArtistProfileRecord';
import {
    ArtistProfileRecordFromJSON,
    ArtistProfileRecordFromJSONTyped,
    ArtistProfileRecordToJSON,
    ArtistProfileRecordToJSONTyped,
} from './ArtistProfileRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfArtistProfileRecord
 */
export interface RequestResponseOfArtistProfileRecord {
    /**
     * 
     * @type {ArtistProfileRecord}
     * @memberof RequestResponseOfArtistProfileRecord
     */
    response?: ArtistProfileRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfArtistProfileRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfArtistProfileRecord interface.
 */
export function instanceOfRequestResponseOfArtistProfileRecord(value: object): value is RequestResponseOfArtistProfileRecord {
    return true;
}

export function RequestResponseOfArtistProfileRecordFromJSON(json: any): RequestResponseOfArtistProfileRecord {
    return RequestResponseOfArtistProfileRecordFromJSONTyped(json, false);
}

export function RequestResponseOfArtistProfileRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfArtistProfileRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ArtistProfileRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfArtistProfileRecordToJSON(json: any): RequestResponseOfArtistProfileRecord {
    return RequestResponseOfArtistProfileRecordToJSONTyped(json, false);
}

export function RequestResponseOfArtistProfileRecordToJSONTyped(value?: RequestResponseOfArtistProfileRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': ArtistProfileRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

