/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedResponseOfUserRecord } from './PagedResponseOfUserRecord';
import {
    PagedResponseOfUserRecordFromJSON,
    PagedResponseOfUserRecordFromJSONTyped,
    PagedResponseOfUserRecordToJSON,
    PagedResponseOfUserRecordToJSONTyped,
} from './PagedResponseOfUserRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfPagedResponseOfUserRecord
 */
export interface RequestResponseOfPagedResponseOfUserRecord {
    /**
     * 
     * @type {PagedResponseOfUserRecord}
     * @memberof RequestResponseOfPagedResponseOfUserRecord
     */
    response?: PagedResponseOfUserRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfPagedResponseOfUserRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfPagedResponseOfUserRecord interface.
 */
export function instanceOfRequestResponseOfPagedResponseOfUserRecord(value: object): value is RequestResponseOfPagedResponseOfUserRecord {
    return true;
}

export function RequestResponseOfPagedResponseOfUserRecordFromJSON(json: any): RequestResponseOfPagedResponseOfUserRecord {
    return RequestResponseOfPagedResponseOfUserRecordFromJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfUserRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfPagedResponseOfUserRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : PagedResponseOfUserRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfPagedResponseOfUserRecordToJSON(json: any): RequestResponseOfPagedResponseOfUserRecord {
    return RequestResponseOfPagedResponseOfUserRecordToJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfUserRecordToJSONTyped(value?: RequestResponseOfPagedResponseOfUserRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': PagedResponseOfUserRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

