/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRecord } from './UserRecord';
import {
    UserRecordFromJSON,
    UserRecordFromJSONTyped,
    UserRecordToJSON,
    UserRecordToJSONTyped,
} from './UserRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfUserRecord
 */
export interface RequestResponseOfUserRecord {
    /**
     * 
     * @type {UserRecord}
     * @memberof RequestResponseOfUserRecord
     */
    response?: UserRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfUserRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfUserRecord interface.
 */
export function instanceOfRequestResponseOfUserRecord(value: object): value is RequestResponseOfUserRecord {
    return true;
}

export function RequestResponseOfUserRecordFromJSON(json: any): RequestResponseOfUserRecord {
    return RequestResponseOfUserRecordFromJSONTyped(json, false);
}

export function RequestResponseOfUserRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfUserRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : UserRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfUserRecordToJSON(json: any): RequestResponseOfUserRecord {
    return RequestResponseOfUserRecordToJSONTyped(json, false);
}

export function RequestResponseOfUserRecordToJSONTyped(value?: RequestResponseOfUserRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': UserRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

