/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { PagedResponseOfTagRecord } from './PagedResponseOfTagRecord';
import {
    PagedResponseOfTagRecordFromJSON,
    PagedResponseOfTagRecordFromJSONTyped,
    PagedResponseOfTagRecordToJSON,
    PagedResponseOfTagRecordToJSONTyped,
} from './PagedResponseOfTagRecord';

/**
 * 
 * @export
 * @interface RequestResponseOfPagedResponseOfTagRecord
 */
export interface RequestResponseOfPagedResponseOfTagRecord {
    /**
     * 
     * @type {PagedResponseOfTagRecord}
     * @memberof RequestResponseOfPagedResponseOfTagRecord
     */
    response?: PagedResponseOfTagRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfPagedResponseOfTagRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfPagedResponseOfTagRecord interface.
 */
export function instanceOfRequestResponseOfPagedResponseOfTagRecord(value: object): value is RequestResponseOfPagedResponseOfTagRecord {
    return true;
}

export function RequestResponseOfPagedResponseOfTagRecordFromJSON(json: any): RequestResponseOfPagedResponseOfTagRecord {
    return RequestResponseOfPagedResponseOfTagRecordFromJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfTagRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfPagedResponseOfTagRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : PagedResponseOfTagRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfPagedResponseOfTagRecordToJSON(json: any): RequestResponseOfPagedResponseOfTagRecord {
    return RequestResponseOfPagedResponseOfTagRecordToJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfTagRecordToJSONTyped(value?: RequestResponseOfPagedResponseOfTagRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': PagedResponseOfTagRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

