/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedResponseOfUserFileRecord } from './PagedResponseOfUserFileRecord';
import {
    PagedResponseOfUserFileRecordFromJSON,
    PagedResponseOfUserFileRecordFromJSONTyped,
    PagedResponseOfUserFileRecordToJSON,
    PagedResponseOfUserFileRecordToJSONTyped,
} from './PagedResponseOfUserFileRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfPagedResponseOfUserFileRecord
 */
export interface RequestResponseOfPagedResponseOfUserFileRecord {
    /**
     * 
     * @type {PagedResponseOfUserFileRecord}
     * @memberof RequestResponseOfPagedResponseOfUserFileRecord
     */
    response?: PagedResponseOfUserFileRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfPagedResponseOfUserFileRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfPagedResponseOfUserFileRecord interface.
 */
export function instanceOfRequestResponseOfPagedResponseOfUserFileRecord(value: object): value is RequestResponseOfPagedResponseOfUserFileRecord {
    return true;
}

export function RequestResponseOfPagedResponseOfUserFileRecordFromJSON(json: any): RequestResponseOfPagedResponseOfUserFileRecord {
    return RequestResponseOfPagedResponseOfUserFileRecordFromJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfUserFileRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfPagedResponseOfUserFileRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : PagedResponseOfUserFileRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfPagedResponseOfUserFileRecordToJSON(json: any): RequestResponseOfPagedResponseOfUserFileRecord {
    return RequestResponseOfPagedResponseOfUserFileRecordToJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfUserFileRecordToJSONTyped(value?: RequestResponseOfPagedResponseOfUserFileRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': PagedResponseOfUserFileRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

