/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedResponseOfArtistProfileRecord } from './PagedResponseOfArtistProfileRecord';
import {
    PagedResponseOfArtistProfileRecordFromJSON,
    PagedResponseOfArtistProfileRecordFromJSONTyped,
    PagedResponseOfArtistProfileRecordToJSON,
    PagedResponseOfArtistProfileRecordToJSONTyped,
} from './PagedResponseOfArtistProfileRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfPagedResponseOfArtistProfileRecord
 */
export interface RequestResponseOfPagedResponseOfArtistProfileRecord {
    /**
     * 
     * @type {PagedResponseOfArtistProfileRecord}
     * @memberof RequestResponseOfPagedResponseOfArtistProfileRecord
     */
    response?: PagedResponseOfArtistProfileRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfPagedResponseOfArtistProfileRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfPagedResponseOfArtistProfileRecord interface.
 */
export function instanceOfRequestResponseOfPagedResponseOfArtistProfileRecord(value: object): value is RequestResponseOfPagedResponseOfArtistProfileRecord {
    return true;
}

export function RequestResponseOfPagedResponseOfArtistProfileRecordFromJSON(json: any): RequestResponseOfPagedResponseOfArtistProfileRecord {
    return RequestResponseOfPagedResponseOfArtistProfileRecordFromJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfArtistProfileRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfPagedResponseOfArtistProfileRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : PagedResponseOfArtistProfileRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfPagedResponseOfArtistProfileRecordToJSON(json: any): RequestResponseOfPagedResponseOfArtistProfileRecord {
    return RequestResponseOfPagedResponseOfArtistProfileRecordToJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfArtistProfileRecordToJSONTyped(value?: RequestResponseOfPagedResponseOfArtistProfileRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': PagedResponseOfArtistProfileRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

