/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponseRecord } from './LoginResponseRecord';
import {
    LoginResponseRecordFromJSON,
    LoginResponseRecordFromJSONTyped,
    LoginResponseRecordToJSON,
    LoginResponseRecordToJSONTyped,
} from './LoginResponseRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfLoginResponseRecord
 */
export interface RequestResponseOfLoginResponseRecord {
    /**
     * 
     * @type {LoginResponseRecord}
     * @memberof RequestResponseOfLoginResponseRecord
     */
    response?: LoginResponseRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfLoginResponseRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfLoginResponseRecord interface.
 */
export function instanceOfRequestResponseOfLoginResponseRecord(value: object): value is RequestResponseOfLoginResponseRecord {
    return true;
}

export function RequestResponseOfLoginResponseRecordFromJSON(json: any): RequestResponseOfLoginResponseRecord {
    return RequestResponseOfLoginResponseRecordFromJSONTyped(json, false);
}

export function RequestResponseOfLoginResponseRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfLoginResponseRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : LoginResponseRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfLoginResponseRecordToJSON(json: any): RequestResponseOfLoginResponseRecord {
    return RequestResponseOfLoginResponseRecordToJSONTyped(json, false);
}

export function RequestResponseOfLoginResponseRecordToJSONTyped(value?: RequestResponseOfLoginResponseRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': LoginResponseRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

