/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagRecord } from './TagRecord';
import {
    TagRecordFromJSON,
    TagRecordFromJSONTyped,
    TagRecordToJSON,
    TagRecordToJSONTyped,
} from './TagRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfTagRecord
 */
export interface RequestResponseOfTagRecord {
    /**
     * 
     * @type {TagRecord}
     * @memberof RequestResponseOfTagRecord
     */
    response?: TagRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfTagRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfTagRecord interface.
 */
export function instanceOfRequestResponseOfTagRecord(value: object): value is RequestResponseOfTagRecord {
    return true;
}

export function RequestResponseOfTagRecordFromJSON(json: any): RequestResponseOfTagRecord {
    return RequestResponseOfTagRecordFromJSONTyped(json, false);
}

export function RequestResponseOfTagRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfTagRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : TagRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfTagRecordToJSON(json: any): RequestResponseOfTagRecord {
    return RequestResponseOfTagRecordToJSONTyped(json, false);
}

export function RequestResponseOfTagRecordToJSONTyped(value?: RequestResponseOfTagRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': TagRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

