/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArtworkRecord } from './ArtworkRecord';
import {
    ArtworkRecordFromJSON,
    ArtworkRecordFromJSONTyped,
    ArtworkRecordToJSON,
    ArtworkRecordToJSONTyped,
} from './ArtworkRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfArtworkRecord
 */
export interface RequestResponseOfArtworkRecord {
    /**
     * 
     * @type {ArtworkRecord}
     * @memberof RequestResponseOfArtworkRecord
     */
    response?: ArtworkRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfArtworkRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfArtworkRecord interface.
 */
export function instanceOfRequestResponseOfArtworkRecord(value: object): value is RequestResponseOfArtworkRecord {
    return true;
}

export function RequestResponseOfArtworkRecordFromJSON(json: any): RequestResponseOfArtworkRecord {
    return RequestResponseOfArtworkRecordFromJSONTyped(json, false);
}

export function RequestResponseOfArtworkRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfArtworkRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ArtworkRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfArtworkRecordToJSON(json: any): RequestResponseOfArtworkRecord {
    return RequestResponseOfArtworkRecordToJSONTyped(json, false);
}

export function RequestResponseOfArtworkRecordToJSONTyped(value?: RequestResponseOfArtworkRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': ArtworkRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

