/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedResponseOfCollectionRecord } from './PagedResponseOfCollectionRecord';
import {
    PagedResponseOfCollectionRecordFromJSON,
    PagedResponseOfCollectionRecordFromJSONTyped,
    PagedResponseOfCollectionRecordToJSON,
    PagedResponseOfCollectionRecordToJSONTyped,
} from './PagedResponseOfCollectionRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfPagedResponseOfCollectionRecord
 */
export interface RequestResponseOfPagedResponseOfCollectionRecord {
    /**
     * 
     * @type {PagedResponseOfCollectionRecord}
     * @memberof RequestResponseOfPagedResponseOfCollectionRecord
     */
    response?: PagedResponseOfCollectionRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfPagedResponseOfCollectionRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfPagedResponseOfCollectionRecord interface.
 */
export function instanceOfRequestResponseOfPagedResponseOfCollectionRecord(value: object): value is RequestResponseOfPagedResponseOfCollectionRecord {
    return true;
}

export function RequestResponseOfPagedResponseOfCollectionRecordFromJSON(json: any): RequestResponseOfPagedResponseOfCollectionRecord {
    return RequestResponseOfPagedResponseOfCollectionRecordFromJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfCollectionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfPagedResponseOfCollectionRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : PagedResponseOfCollectionRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfPagedResponseOfCollectionRecordToJSON(json: any): RequestResponseOfPagedResponseOfCollectionRecord {
    return RequestResponseOfPagedResponseOfCollectionRecordToJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfCollectionRecordToJSONTyped(value?: RequestResponseOfPagedResponseOfCollectionRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': PagedResponseOfCollectionRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

