/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionRecord } from './CollectionRecord';
import {
    CollectionRecordFromJSON,
    CollectionRecordFromJSONTyped,
    CollectionRecordToJSON,
    CollectionRecordToJSONTyped,
} from './CollectionRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfCollectionRecord
 */
export interface RequestResponseOfCollectionRecord {
    /**
     * 
     * @type {CollectionRecord}
     * @memberof RequestResponseOfCollectionRecord
     */
    response?: CollectionRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfCollectionRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfCollectionRecord interface.
 */
export function instanceOfRequestResponseOfCollectionRecord(value: object): value is RequestResponseOfCollectionRecord {
    return true;
}

export function RequestResponseOfCollectionRecordFromJSON(json: any): RequestResponseOfCollectionRecord {
    return RequestResponseOfCollectionRecordFromJSONTyped(json, false);
}

export function RequestResponseOfCollectionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfCollectionRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : CollectionRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfCollectionRecordToJSON(json: any): RequestResponseOfCollectionRecord {
    return RequestResponseOfCollectionRecordToJSONTyped(json, false);
}

export function RequestResponseOfCollectionRecordToJSONTyped(value?: RequestResponseOfCollectionRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': CollectionRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

