/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedResponseOfArtworkRecord } from './PagedResponseOfArtworkRecord';
import {
    PagedResponseOfArtworkRecordFromJSON,
    PagedResponseOfArtworkRecordFromJSONTyped,
    PagedResponseOfArtworkRecordToJSON,
    PagedResponseOfArtworkRecordToJSONTyped,
} from './PagedResponseOfArtworkRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfPagedResponseOfArtworkRecord
 */
export interface RequestResponseOfPagedResponseOfArtworkRecord {
    /**
     * 
     * @type {PagedResponseOfArtworkRecord}
     * @memberof RequestResponseOfPagedResponseOfArtworkRecord
     */
    response?: PagedResponseOfArtworkRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfPagedResponseOfArtworkRecord
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfPagedResponseOfArtworkRecord interface.
 */
export function instanceOfRequestResponseOfPagedResponseOfArtworkRecord(value: object): value is RequestResponseOfPagedResponseOfArtworkRecord {
    return true;
}

export function RequestResponseOfPagedResponseOfArtworkRecordFromJSON(json: any): RequestResponseOfPagedResponseOfArtworkRecord {
    return RequestResponseOfPagedResponseOfArtworkRecordFromJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfArtworkRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfPagedResponseOfArtworkRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : PagedResponseOfArtworkRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfPagedResponseOfArtworkRecordToJSON(json: any): RequestResponseOfPagedResponseOfArtworkRecord {
    return RequestResponseOfPagedResponseOfArtworkRecordToJSONTyped(json, false);
}

export function RequestResponseOfPagedResponseOfArtworkRecordToJSONTyped(value?: RequestResponseOfPagedResponseOfArtworkRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': PagedResponseOfArtworkRecordToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

