/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RequestResponseOfint
 */
export interface RequestResponseOfint {
    /**
     * 
     * @type {number}
     * @memberof RequestResponseOfint
     */
    response: number;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RequestResponseOfint
     */
    errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RequestResponseOfint interface.
 */
export function instanceOfRequestResponseOfint(value: object): value is RequestResponseOfint {
    if (!('response' in value) || value['response'] === undefined) return false;
    return true;
}

export function RequestResponseOfintFromJSON(json: any): RequestResponseOfint {
    return RequestResponseOfintFromJSONTyped(json, false);
}

export function RequestResponseOfintFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResponseOfint {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'],
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RequestResponseOfintToJSON(json: any): RequestResponseOfint {
    return RequestResponseOfintToJSONTyped(json, false);
}

export function RequestResponseOfintToJSONTyped(value?: RequestResponseOfint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': value['response'],
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

