/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagAddRecord
 */
export interface TagAddRecord {
    /**
     * 
     * @type {string}
     * @memberof TagAddRecord
     */
    name: string;
}

/**
 * Check if a given object implements the TagAddRecord interface.
 */
export function instanceOfTagAddRecord(value: object): value is TagAddRecord {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TagAddRecordFromJSON(json: any): TagAddRecord {
    return TagAddRecordFromJSONTyped(json, false);
}

export function TagAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TagAddRecordToJSON(json: any): TagAddRecord {
    return TagAddRecordToJSONTyped(json, false);
}

export function TagAddRecordToJSONTyped(value?: TagAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

