/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagRecord
 */
export interface TagRecord {
    /**
     * 
     * @type {string}
     * @memberof TagRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TagRecord
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TagRecord
     */
    artworkIds?: Array<string> | null;
}

/**
 * Check if a given object implements the TagRecord interface.
 */
export function instanceOfTagRecord(value: object): value is TagRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TagRecordFromJSON(json: any): TagRecord {
    return TagRecordFromJSONTyped(json, false);
}

export function TagRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'artworkIds': json['artworkIds'] == null ? undefined : json['artworkIds'],
    };
}

export function TagRecordToJSON(json: any): TagRecord {
    return TagRecordToJSONTyped(json, false);
}

export function TagRecordToJSONTyped(value?: TagRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'artworkIds': value['artworkIds'],
    };
}

