/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ArtistProfileAddRecord,
  ArtistProfileUpdateRecord,
  RequestResponse,
  RequestResponseOfArtistProfileRecord,
  RequestResponseOfPagedResponseOfArtistProfileRecord,
} from '../models/index';
import {
    ArtistProfileAddRecordFromJSON,
    ArtistProfileAddRecordToJSON,
    ArtistProfileUpdateRecordFromJSON,
    ArtistProfileUpdateRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
    RequestResponseOfArtistProfileRecordFromJSON,
    RequestResponseOfArtistProfileRecordToJSON,
    RequestResponseOfPagedResponseOfArtistProfileRecordFromJSON,
    RequestResponseOfPagedResponseOfArtistProfileRecordToJSON,
} from '../models/index';

export interface ApiArtistProfileAddPostRequest {
    artistProfileAddRecord: ArtistProfileAddRecord;
}

export interface ApiArtistProfileDeleteIdDeleteRequest {
    id: string;
}

export interface ApiArtistProfileGetByIdIdGetRequest {
    id: string;
}

export interface ApiArtistProfileGetByUserIdUserIdGetRequest {
    userId: string;
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiArtistProfileGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiArtistProfileUpdatePutRequest {
    artistProfileUpdateRecord: ArtistProfileUpdateRecord;
}

/**
 * 
 */
export class ArtistProfileApi extends runtime.BaseAPI {

    /**
     */
    async apiArtistProfileAddPostRaw(requestParameters: ApiArtistProfileAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['artistProfileAddRecord'] == null) {
            throw new runtime.RequiredError(
                'artistProfileAddRecord',
                'Required parameter "artistProfileAddRecord" was null or undefined when calling apiArtistProfileAddPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/ArtistProfile/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ArtistProfileAddRecordToJSON(requestParameters['artistProfileAddRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiArtistProfileAddPost(requestParameters: ApiArtistProfileAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiArtistProfileAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtistProfileDeleteIdDeleteRaw(requestParameters: ApiArtistProfileDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiArtistProfileDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/ArtistProfile/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiArtistProfileDeleteIdDelete(requestParameters: ApiArtistProfileDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiArtistProfileDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtistProfileGetByIdIdGetRaw(requestParameters: ApiArtistProfileGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfArtistProfileRecord>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiArtistProfileGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/ArtistProfile/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfArtistProfileRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiArtistProfileGetByIdIdGet(requestParameters: ApiArtistProfileGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfArtistProfileRecord> {
        const response = await this.apiArtistProfileGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtistProfileGetByUserIdUserIdGetRaw(requestParameters: ApiArtistProfileGetByUserIdUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfArtistProfileRecord>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiArtistProfileGetByUserIdUserIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/ArtistProfile/GetByUserId/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfArtistProfileRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiArtistProfileGetByUserIdUserIdGet(requestParameters: ApiArtistProfileGetByUserIdUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfArtistProfileRecord> {
        const response = await this.apiArtistProfileGetByUserIdUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtistProfileGetPageGetRaw(requestParameters: ApiArtistProfileGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfPagedResponseOfArtistProfileRecord>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/ArtistProfile/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfPagedResponseOfArtistProfileRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiArtistProfileGetPageGet(requestParameters: ApiArtistProfileGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfPagedResponseOfArtistProfileRecord> {
        const response = await this.apiArtistProfileGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtistProfileUpdatePutRaw(requestParameters: ApiArtistProfileUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['artistProfileUpdateRecord'] == null) {
            throw new runtime.RequiredError(
                'artistProfileUpdateRecord',
                'Required parameter "artistProfileUpdateRecord" was null or undefined when calling apiArtistProfileUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/ArtistProfile/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ArtistProfileUpdateRecordToJSON(requestParameters['artistProfileUpdateRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiArtistProfileUpdatePut(requestParameters: ApiArtistProfileUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiArtistProfileUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
