/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestResponse,
  RequestResponseOfArtworkRecord,
  RequestResponseOfPagedResponseOfArtworkRecord,
} from '../models/index';
import {
    RequestResponseFromJSON,
    RequestResponseToJSON,
    RequestResponseOfArtworkRecordFromJSON,
    RequestResponseOfArtworkRecordToJSON,
    RequestResponseOfPagedResponseOfArtworkRecordFromJSON,
    RequestResponseOfPagedResponseOfArtworkRecordToJSON,
} from '../models/index';

export interface ApiArtworkAddPostRequest {
    title?: string;
    description?: string;
    imageFile?: Blob;
    artistProfileId?: string;
}

export interface ApiArtworkDeleteIdDeleteRequest {
    id: string;
}

export interface ApiArtworkGetByArtistProfileArtistProfileIdGetRequest {
    artistProfileId: string;
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiArtworkGetByIdIdGetRequest {
    id: string;
}

export interface ApiArtworkGetImageIdGetRequest {
    id: string;
}

export interface ApiArtworkGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiArtworkIncrementSharesIdPutRequest {
    id: string;
}

export interface ApiArtworkIncrementViewsIdPutRequest {
    id: string;
}

export interface ApiArtworkUpdatePutRequest {
    id?: string;
    artistProfileId?: string;
    title?: string;
    description?: string;
    imageFile?: Blob;
    tagIds?: Array<string>;
}

/**
 * 
 */
export class ArtworkApi extends runtime.BaseAPI {

    /**
     */
    async apiArtworkAddPostRaw(requestParameters: ApiArtworkAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['title'] != null) {
            formParams.append('Title', requestParameters['title'] as any);
        }

        if (requestParameters['description'] != null) {
            formParams.append('Description', requestParameters['description'] as any);
        }

        if (requestParameters['imageFile'] != null) {
            formParams.append('ImageFile', requestParameters['imageFile'] as any);
        }

        if (requestParameters['artistProfileId'] != null) {
            formParams.append('ArtistProfileId', requestParameters['artistProfileId'] as any);
        }

        const response = await this.request({
            path: `/api/Artwork/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkAddPost(requestParameters: ApiArtworkAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiArtworkAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtworkDeleteIdDeleteRaw(requestParameters: ApiArtworkDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiArtworkDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Artwork/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkDeleteIdDelete(requestParameters: ApiArtworkDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiArtworkDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtworkGetByArtistProfileArtistProfileIdGetRaw(requestParameters: ApiArtworkGetByArtistProfileArtistProfileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfPagedResponseOfArtworkRecord>> {
        if (requestParameters['artistProfileId'] == null) {
            throw new runtime.RequiredError(
                'artistProfileId',
                'Required parameter "artistProfileId" was null or undefined when calling apiArtworkGetByArtistProfileArtistProfileIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Artwork/GetByArtistProfile/{artistProfileId}`.replace(`{${"artistProfileId"}}`, encodeURIComponent(String(requestParameters['artistProfileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfPagedResponseOfArtworkRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkGetByArtistProfileArtistProfileIdGet(requestParameters: ApiArtworkGetByArtistProfileArtistProfileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfPagedResponseOfArtworkRecord> {
        const response = await this.apiArtworkGetByArtistProfileArtistProfileIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtworkGetByIdIdGetRaw(requestParameters: ApiArtworkGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfArtworkRecord>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiArtworkGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Artwork/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfArtworkRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkGetByIdIdGet(requestParameters: ApiArtworkGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfArtworkRecord> {
        const response = await this.apiArtworkGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtworkGetImageIdGetRaw(requestParameters: ApiArtworkGetImageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiArtworkGetImageIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Artwork/GetImage/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     */
    async apiArtworkGetImageIdGet(requestParameters: ApiArtworkGetImageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiArtworkGetImageIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtworkGetPageGetRaw(requestParameters: ApiArtworkGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfPagedResponseOfArtworkRecord>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Artwork/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfPagedResponseOfArtworkRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkGetPageGet(requestParameters: ApiArtworkGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfPagedResponseOfArtworkRecord> {
        const response = await this.apiArtworkGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtworkIncrementSharesIdPutRaw(requestParameters: ApiArtworkIncrementSharesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiArtworkIncrementSharesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Artwork/IncrementShares/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkIncrementSharesIdPut(requestParameters: ApiArtworkIncrementSharesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiArtworkIncrementSharesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtworkIncrementViewsIdPutRaw(requestParameters: ApiArtworkIncrementViewsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiArtworkIncrementViewsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Artwork/IncrementViews/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkIncrementViewsIdPut(requestParameters: ApiArtworkIncrementViewsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiArtworkIncrementViewsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtworkUpdatePutRaw(requestParameters: ApiArtworkUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('Id', requestParameters['id'] as any);
        }

        if (requestParameters['artistProfileId'] != null) {
            formParams.append('ArtistProfileId', requestParameters['artistProfileId'] as any);
        }

        if (requestParameters['title'] != null) {
            formParams.append('Title', requestParameters['title'] as any);
        }

        if (requestParameters['description'] != null) {
            formParams.append('Description', requestParameters['description'] as any);
        }

        if (requestParameters['imageFile'] != null) {
            formParams.append('ImageFile', requestParameters['imageFile'] as any);
        }

        if (requestParameters['tagIds'] != null) {
            formParams.append('TagIds', requestParameters['tagIds']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        const response = await this.request({
            path: `/api/Artwork/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkUpdatePut(requestParameters: ApiArtworkUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiArtworkUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
