/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestResponse,
  RequestResponseOfint,
} from '../models/index';
import {
    RequestResponseFromJSON,
    RequestResponseToJSON,
    RequestResponseOfintFromJSON,
    RequestResponseOfintToJSON,
} from '../models/index';

export interface ApiArtworkLikeGetLikesGetRequest {
    artworkId?: string;
}

export interface ApiArtworkLikeLikePostRequest {
    body: string;
}

export interface ApiArtworkLikeUnlikeDeleteRequest {
    body: string;
}

/**
 * 
 */
export class ArtworkLikeApi extends runtime.BaseAPI {

    /**
     */
    async apiArtworkLikeGetLikesGetRaw(requestParameters: ApiArtworkLikeGetLikesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfint>> {
        const queryParameters: any = {};

        if (requestParameters['artworkId'] != null) {
            queryParameters['artworkId'] = requestParameters['artworkId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/ArtworkLike/GetLikes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfintFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkLikeGetLikesGet(requestParameters: ApiArtworkLikeGetLikesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfint> {
        const response = await this.apiArtworkLikeGetLikesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtworkLikeLikePostRaw(requestParameters: ApiArtworkLikeLikePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiArtworkLikeLikePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/ArtworkLike/Like`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkLikeLikePost(requestParameters: ApiArtworkLikeLikePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiArtworkLikeLikePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiArtworkLikeUnlikeDeleteRaw(requestParameters: ApiArtworkLikeUnlikeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiArtworkLikeUnlikeDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/ArtworkLike/Unlike`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiArtworkLikeUnlikeDelete(requestParameters: ApiArtworkLikeUnlikeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiArtworkLikeUnlikeDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
