/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoginRecord,
  RegisterRecord,
  RequestResponse,
  RequestResponseOfLoginResponseRecord,
} from '../models/index';
import {
    LoginRecordFromJSON,
    LoginRecordToJSON,
    RegisterRecordFromJSON,
    RegisterRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
    RequestResponseOfLoginResponseRecordFromJSON,
    RequestResponseOfLoginResponseRecordToJSON,
} from '../models/index';

export interface ApiAuthorizationLoginPostRequest {
    loginRecord: LoginRecord;
}

export interface ApiAuthorizationRegisterPostRequest {
    registerRecord: RegisterRecord;
}

/**
 * 
 */
export class AuthorizationApi extends runtime.BaseAPI {

    /**
     */
    async apiAuthorizationLoginPostRaw(requestParameters: ApiAuthorizationLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfLoginResponseRecord>> {
        if (requestParameters['loginRecord'] == null) {
            throw new runtime.RequiredError(
                'loginRecord',
                'Required parameter "loginRecord" was null or undefined when calling apiAuthorizationLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authorization/Login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRecordToJSON(requestParameters['loginRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfLoginResponseRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthorizationLoginPost(requestParameters: ApiAuthorizationLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfLoginResponseRecord> {
        const response = await this.apiAuthorizationLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthorizationRegisterPostRaw(requestParameters: ApiAuthorizationRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['registerRecord'] == null) {
            throw new runtime.RequiredError(
                'registerRecord',
                'Required parameter "registerRecord" was null or undefined when calling apiAuthorizationRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authorization/Register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRecordToJSON(requestParameters['registerRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthorizationRegisterPost(requestParameters: ApiAuthorizationRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiAuthorizationRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
