/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionAddRecord,
  CollectionArtworkRecord,
  CollectionUpdateRecord,
  RequestResponse,
  RequestResponseOfCollectionRecord,
  RequestResponseOfPagedResponseOfCollectionRecord,
} from '../models/index';
import {
    CollectionAddRecordFromJSON,
    CollectionAddRecordToJSON,
    CollectionArtworkRecordFromJSON,
    CollectionArtworkRecordToJSON,
    CollectionUpdateRecordFromJSON,
    CollectionUpdateRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
    RequestResponseOfCollectionRecordFromJSON,
    RequestResponseOfCollectionRecordToJSON,
    RequestResponseOfPagedResponseOfCollectionRecordFromJSON,
    RequestResponseOfPagedResponseOfCollectionRecordToJSON,
} from '../models/index';

export interface ApiCollectionAddArtworkPutRequest {
    collectionArtworkRecord: CollectionArtworkRecord;
}

export interface ApiCollectionAddPostRequest {
    collectionAddRecord: CollectionAddRecord;
}

export interface ApiCollectionDeleteIdDeleteRequest {
    id: string;
}

export interface ApiCollectionGetByIdIdGetRequest {
    id: string;
}

export interface ApiCollectionGetByUserIdUserIdGetRequest {
    userId: string;
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiCollectionGetOwnCollectionsGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiCollectionGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiCollectionRemoveArtworkDeleteRequest {
    collectionArtworkRecord: CollectionArtworkRecord;
}

export interface ApiCollectionUpdatePutRequest {
    collectionUpdateRecord: CollectionUpdateRecord;
}

/**
 * 
 */
export class CollectionApi extends runtime.BaseAPI {

    /**
     */
    async apiCollectionAddArtworkPutRaw(requestParameters: ApiCollectionAddArtworkPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['collectionArtworkRecord'] == null) {
            throw new runtime.RequiredError(
                'collectionArtworkRecord',
                'Required parameter "collectionArtworkRecord" was null or undefined when calling apiCollectionAddArtworkPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Collection/AddArtwork`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionArtworkRecordToJSON(requestParameters['collectionArtworkRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCollectionAddArtworkPut(requestParameters: ApiCollectionAddArtworkPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCollectionAddArtworkPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCollectionAddPostRaw(requestParameters: ApiCollectionAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['collectionAddRecord'] == null) {
            throw new runtime.RequiredError(
                'collectionAddRecord',
                'Required parameter "collectionAddRecord" was null or undefined when calling apiCollectionAddPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Collection/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionAddRecordToJSON(requestParameters['collectionAddRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCollectionAddPost(requestParameters: ApiCollectionAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCollectionAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCollectionDeleteIdDeleteRaw(requestParameters: ApiCollectionDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCollectionDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Collection/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCollectionDeleteIdDelete(requestParameters: ApiCollectionDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCollectionDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCollectionGetByIdIdGetRaw(requestParameters: ApiCollectionGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfCollectionRecord>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCollectionGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Collection/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfCollectionRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiCollectionGetByIdIdGet(requestParameters: ApiCollectionGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfCollectionRecord> {
        const response = await this.apiCollectionGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCollectionGetByUserIdUserIdGetRaw(requestParameters: ApiCollectionGetByUserIdUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfPagedResponseOfCollectionRecord>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiCollectionGetByUserIdUserIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Collection/GetByUserId/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfPagedResponseOfCollectionRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiCollectionGetByUserIdUserIdGet(requestParameters: ApiCollectionGetByUserIdUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfPagedResponseOfCollectionRecord> {
        const response = await this.apiCollectionGetByUserIdUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCollectionGetOwnCollectionsGetRaw(requestParameters: ApiCollectionGetOwnCollectionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfPagedResponseOfCollectionRecord>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Collection/GetOwnCollections`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfPagedResponseOfCollectionRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiCollectionGetOwnCollectionsGet(requestParameters: ApiCollectionGetOwnCollectionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfPagedResponseOfCollectionRecord> {
        const response = await this.apiCollectionGetOwnCollectionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCollectionGetPageGetRaw(requestParameters: ApiCollectionGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfPagedResponseOfCollectionRecord>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Collection/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfPagedResponseOfCollectionRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiCollectionGetPageGet(requestParameters: ApiCollectionGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfPagedResponseOfCollectionRecord> {
        const response = await this.apiCollectionGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCollectionRemoveArtworkDeleteRaw(requestParameters: ApiCollectionRemoveArtworkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['collectionArtworkRecord'] == null) {
            throw new runtime.RequiredError(
                'collectionArtworkRecord',
                'Required parameter "collectionArtworkRecord" was null or undefined when calling apiCollectionRemoveArtworkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Collection/RemoveArtwork`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionArtworkRecordToJSON(requestParameters['collectionArtworkRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCollectionRemoveArtworkDelete(requestParameters: ApiCollectionRemoveArtworkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCollectionRemoveArtworkDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCollectionUpdatePutRaw(requestParameters: ApiCollectionUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['collectionUpdateRecord'] == null) {
            throw new runtime.RequiredError(
                'collectionUpdateRecord',
                'Required parameter "collectionUpdateRecord" was null or undefined when calling apiCollectionUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Collection/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionUpdateRecordToJSON(requestParameters['collectionUpdateRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCollectionUpdatePut(requestParameters: ApiCollectionUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCollectionUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
