/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FeedbackSubmitRecord,
  RequestResponse,
} from '../models/index';
import {
    FeedbackSubmitRecordFromJSON,
    FeedbackSubmitRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiFeedbackFormSubmitPostRequest {
    feedbackSubmitRecord: FeedbackSubmitRecord;
}

/**
 * 
 */
export class FeedbackFormApi extends runtime.BaseAPI {

    /**
     */
    async apiFeedbackFormSubmitPostRaw(requestParameters: ApiFeedbackFormSubmitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['feedbackSubmitRecord'] == null) {
            throw new runtime.RequiredError(
                'feedbackSubmitRecord',
                'Required parameter "feedbackSubmitRecord" was null or undefined when calling apiFeedbackFormSubmitPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/FeedbackForm/Submit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FeedbackSubmitRecordToJSON(requestParameters['feedbackSubmitRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiFeedbackFormSubmitPost(requestParameters: ApiFeedbackFormSubmitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiFeedbackFormSubmitPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
