/* tslint:disable */
/* eslint-disable */
/**
 * ArtOnline.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestResponse,
  RequestResponseOfPagedResponseOfTagRecord,
  RequestResponseOfTagRecord,
  TagAddRecord,
  TagRecord,
} from '../models/index';
import {
    RequestResponseFromJSON,
    RequestResponseToJSON,
    RequestResponseOfPagedResponseOfTagRecordFromJSON,
    RequestResponseOfPagedResponseOfTagRecordToJSON,
    RequestResponseOfTagRecordFromJSON,
    RequestResponseOfTagRecordToJSON,
    TagAddRecordFromJSON,
    TagAddRecordToJSON,
    TagRecordFromJSON,
    TagRecordToJSON,
} from '../models/index';

export interface ApiTagAddPostRequest {
    tagAddRecord: TagAddRecord;
}

export interface ApiTagDeleteDeleteRequest {
    body: string;
}

export interface ApiTagGetIdGetRequest {
    id: string;
}

export interface ApiTagGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiTagUpdatePutRequest {
    tagRecord: TagRecord;
}

/**
 * 
 */
export class TagApi extends runtime.BaseAPI {

    /**
     */
    async apiTagAddPostRaw(requestParameters: ApiTagAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['tagAddRecord'] == null) {
            throw new runtime.RequiredError(
                'tagAddRecord',
                'Required parameter "tagAddRecord" was null or undefined when calling apiTagAddPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Tag/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TagAddRecordToJSON(requestParameters['tagAddRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiTagAddPost(requestParameters: ApiTagAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiTagAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTagDeleteDeleteRaw(requestParameters: ApiTagDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiTagDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Tag/Delete`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiTagDeleteDelete(requestParameters: ApiTagDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiTagDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTagGetIdGetRaw(requestParameters: ApiTagGetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfTagRecord>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTagGetIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Tag/Get/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfTagRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiTagGetIdGet(requestParameters: ApiTagGetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfTagRecord> {
        const response = await this.apiTagGetIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTagGetPageGetRaw(requestParameters: ApiTagGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponseOfPagedResponseOfTagRecord>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Tag/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseOfPagedResponseOfTagRecordFromJSON(jsonValue));
    }

    /**
     */
    async apiTagGetPageGet(requestParameters: ApiTagGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponseOfPagedResponseOfTagRecord> {
        const response = await this.apiTagGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTagUpdatePutRaw(requestParameters: ApiTagUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['tagRecord'] == null) {
            throw new runtime.RequiredError(
                'tagRecord',
                'Required parameter "tagRecord" was null or undefined when calling apiTagUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Tag/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TagRecordToJSON(requestParameters['tagRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiTagUpdatePut(requestParameters: ApiTagUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiTagUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
